// ==============================================================================
// 👜 BAG CATALOG & 50 VERIFIED BAG PRODUCTS - Sampha Ra (สัมภาระ)
// ==============================================================================

export const INITIAL_CATEGORIES = [
    { id: 'all', name: 'All Bags', name_th: 'กระเป๋าทั้งหมด', icon: 'layout-grid' },
    { id: 'tote', name: 'Tote Bags', name_th: 'กระเป๋าโท้ท', icon: 'shopping-bag' },
    { id: 'crossbody', name: 'Crossbody', name_th: 'กระเป๋าสะพายข้าง', icon: 'shield' },
    { id: 'shoulder', name: 'Shoulder Bags', name_th: 'กระเป๋าสะพายไหล่', icon: 'briefcase' },
    { id: 'backpack', name: 'Backpacks', name_th: 'เป้สะพายหลัง', icon: 'package' },
    { id: 'travel', name: 'Travel Bags', name_th: 'กระเป๋าเดินทาง', icon: 'compass' },
    { id: 'mini', name: 'Mini & Wallets', name_th: 'กระเป๋าสตางค์และมินิ', icon: 'credit-card' }
];

export const INITIAL_PRODUCTS = [
    // --- 1. TOTE BAGS (10 items) ---
    {
        id: 'prod-001',
        sku: 'BAG-TOT-01',
        name: 'Sampha Ra Classic Leather Tote',
        name_th: 'กระเป๋าโท้ทหนังแท้คลาสสิก',
        category: 'tote',
        price: 3890.00,
        cost_price: 1950.00,
        stock: 18,
        image_url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าโท้ทหนังแท้เกรดพรีเมียม สวยหรู จุของได้เยอะ เหมาะสำหรับทำงานและชีวิตประจำวัน',
        material: 'หนังวัวแท้ Grain Leather',
        dimensions: '36 x 28 x 14 cm',
        color: 'Cognac Brown',
        badge: 'BESTSELLER',
        is_active: true
    },
    {
        id: 'prod-002',
        sku: 'BAG-CAN-02',
        name: 'Minimalist Canvas Everyday Bag',
        name_th: 'กระเป๋าผ้าแคนวาสมินิมอล',
        category: 'tote',
        price: 1290.00,
        cost_price: 550.00,
        stock: 35,
        image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าผ้าแคนวาสเนื้อหนา 16oz ทรงมินิมอล ใส่โน้ตบุ๊ก 14 นิ้วได้ มีช่องแยกด้านใน',
        material: 'Heavy Canvas 16oz & Leather Trim',
        dimensions: '38 x 32 x 12 cm',
        color: 'Off-White / Natural',
        badge: 'HOT',
        is_active: true
    },
    {
        id: 'prod-003',
        sku: 'BAG-BUC-08',
        name: 'Artisan Woven Bucket Tote',
        name_th: 'กระเป๋าทรงถังงานสานผสมหนัง',
        category: 'tote',
        price: 2150.00,
        cost_price: 950.00,
        stock: 15,
        image_url: 'https://images.unsplash.com/photo-1614179689702-355944cf0918?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าทรงถังลายสานประณีต มีถุงผ้าซับในรูดปิดได้ สไตล์ Natural Chic',
        material: 'Handwoven Raffia & Tan Leather',
        dimensions: '22 x 25 x 15 cm',
        color: 'Natural Raffia',
        badge: 'HOT',
        is_active: true
    },
    {
        id: 'prod-004',
        sku: 'BAG-FOL-11',
        name: 'Executive Laptop Folio Bag',
        name_th: 'กระเป๋าใส่แล็ปท็อปหนังเรียบหรู',
        category: 'tote',
        price: 3490.00,
        cost_price: 1600.00,
        stock: 12,
        image_url: 'https://images.unsplash.com/photo-1524498250077-390f9e378fc0?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าเอกสารและแล็ปท็อปทรง Slim เรียบหรู เสริมภาพลักษณ์มืออาชีพ',
        material: 'Saffiano Leather',
        dimensions: '39 x 29 x 5 cm',
        color: 'Midnight Navy',
        badge: 'NEW',
        is_active: true
    },
    {
        id: 'prod-005',
        sku: 'BAG-TOT-05',
        name: 'Grand Horizon Oversized Shopper',
        name_th: 'กระเป๋าช้อปเปอร์ใบใหญ่จุใจ',
        category: 'tote',
        price: 2890.00,
        cost_price: 1300.00,
        stock: 20,
        image_url: 'https://images.unsplash.com/photo-1590736704728-f4730bb30770?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าช้อปเปอร์ขนาดใหญ่พิเศษ น้ำหนักเบา จุสัมภาระได้ครบครัน เหมาะกับทุกทริป',
        material: 'Premium Vegan Nappa',
        dimensions: '42 x 34 x 16 cm',
        color: 'Caramel Latte',
        badge: 'HOT',
        is_active: true
    },
    {
        id: 'prod-006',
        sku: 'BAG-TOT-06',
        name: 'Riviera Straw Beach Tote',
        name_th: 'กระเป๋าสานริเวียร่าสไตล์ซัมเมอร์',
        category: 'tote',
        price: 1890.00,
        cost_price: 800.00,
        stock: 24,
        image_url: 'https://images.unsplash.com/photo-1575032617751-6ddec2089882?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าสานธรรมชาติพร้อมหูหิ้วหนังแท้ สไตล์พักผ่อนริมทะเลและวันสบายๆ',
        material: 'Natural Straw & Calf Leather',
        dimensions: '35 x 30 x 14 cm',
        color: 'Beige Straw & Cognac',
        badge: 'NEW',
        is_active: true
    },
    {
        id: 'prod-007',
        sku: 'BAG-TOT-07',
        name: 'Monochrome Canvas Book Tote',
        name_th: 'กระเป๋าบุ๊คโท้ทลายโมโนโครม',
        category: 'tote',
        price: 1650.00,
        cost_price: 700.00,
        stock: 30,
        image_url: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าผ้าทรงเหลี่ยมตั้งอยู่ทรง ลายกราฟิกคลาสสิก ใส่หนังสือและไอแพดได้สบาย',
        material: 'Jacquard Fabric & Canvas',
        dimensions: '32 x 26 x 11 cm',
        color: 'Black & Ivory',
        badge: '',
        is_active: true
    },
    {
        id: 'prod-008',
        sku: 'BAG-TOT-08',
        name: 'Oxford Structured Work Tote',
        name_th: 'กระเป๋าทำงานอ็อกซ์ฟอร์ดทรงเป๊ะ',
        category: 'tote',
        price: 4150.00,
        cost_price: 2000.00,
        stock: 14,
        image_url: 'https://images.unsplash.com/photo-1598532163257-ae3c6b2524b6?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าทำงานทรงสุภาพ แบ่ง 3 ช่องใหญ่ ซิปกลางปิดมิดชิด ปกป้องของมีค่า',
        material: 'Epsom Textured Leather',
        dimensions: '37 x 27 x 13 cm',
        color: 'Charcoal Black',
        badge: 'BESTSELLER',
        is_active: true
    },
    {
        id: 'prod-009',
        sku: 'BAG-TOT-09',
        name: 'Pleated Velvet Day Tote',
        name_th: 'กระเป๋าโท้ทผ้ากำมะหยี่อัดพลีท',
        category: 'tote',
        price: 1950.00,
        cost_price: 850.00,
        stock: 16,
        image_url: 'https://images.unsplash.com/photo-1587467512961-120760940315?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าผ้ากำมะหยี่เนื้อนุ่มอัดพลีทลอนสวย สัมผัสหรูหรา น้ำหนักเบาพกพาง่าย',
        material: 'Soft Velvet Pleats',
        dimensions: '34 x 36 x 8 cm',
        color: 'Emerald Green',
        badge: 'LIMITED',
        is_active: true
    },
    {
        id: 'prod-010',
        sku: 'BAG-TOT-10',
        name: 'Soft Leather Slouchy Hobo Tote',
        name_th: 'กระเป๋าโท้ทหนังนุ่มทรง Slouchy',
        category: 'tote',
        price: 3290.00,
        cost_price: 1500.00,
        stock: 19,
        image_url: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าหนังทรงทิ้งตัว นุ่มนวลแนบตัว สไตล์มินิมอลญี่ปุ่น สะพายคล่องตัวทุกวัน',
        material: 'Soft Pebble Vegan Leather',
        dimensions: '40 x 30 x 15 cm',
        color: 'Taupe Grey',
        badge: 'NEW',
        is_active: true
    },

    // --- 2. CROSSBODY BAGS (10 items) ---
    {
        id: 'prod-011',
        sku: 'BAG-CRB-03',
        name: 'Urban Crossbody Saddle Bag',
        name_th: 'กระเป๋าสะพายข้างทรงแซดเดิล',
        category: 'crossbody',
        price: 2450.00,
        cost_price: 1100.00,
        stock: 14,
        image_url: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าสะพายข้างทรงแซดเดิล โค้งมน อะไหล่ทองรมดำ ปรับสายสั้นยาวได้',
        material: 'Smooth PU Leather & Gold Hardware',
        dimensions: '24 x 18 x 7 cm',
        color: 'Noir Black',
        badge: 'NEW',
        is_active: true
    },
    {
        id: 'prod-012',
        sku: 'BAG-CRB-12',
        name: 'Sunset Mini Box Crossbody',
        name_th: 'กระเป๋าสะพายมินิบ็อกซ์รุ่นพิเศษ',
        category: 'crossbody',
        price: 1890.00,
        cost_price: 800.00,
        stock: 22,
        image_url: 'https://images.unsplash.com/photo-1566150902887-9679ec155ba0?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าทรงกล่องมินิดีไซน์น่ารัก ใส่สมาร์ตโฟนได้ทุกรุ่น ล็อคแม่เหล็กเปิดปิดง่าย',
        material: 'Smooth Box Leather',
        dimensions: '18 x 13 x 6 cm',
        color: 'Terracotta Orange',
        badge: 'LIMITED',
        is_active: true
    },
    {
        id: 'prod-013',
        sku: 'BAG-CRB-13',
        name: 'Metropolitan Camera Bag',
        name_th: 'กระเป๋ากล้องหนังสะพายข้าง',
        category: 'crossbody',
        price: 2190.00,
        cost_price: 950.00,
        stock: 18,
        image_url: 'https://images.unsplash.com/photo-1591348278863-a8fb3887e2aa?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าทรง Camera Bag สปอร์ตแคชชวล มีช่องซิปหน้า 2 ช่อง ใส่กระเป๋าสตางค์และมือถือครบ',
        material: 'Water-resistant Microfiber Leather',
        dimensions: '21 x 15 x 8 cm',
        color: 'Olive Green',
        badge: 'HOT',
        is_active: true
    },
    {
        id: 'prod-014',
        sku: 'BAG-CRB-14',
        name: 'Aura Half-Moon Crossbody',
        name_th: 'กระเป๋าสะพายข้างทรงฮาล์ฟมูน',
        category: 'crossbody',
        price: 2650.00,
        cost_price: 1200.00,
        stock: 16,
        image_url: 'https://images.unsplash.com/photo-1577733966973-d680bffd2e80?auto=format&fit=crop&w=800&q=80',
        description: 'ทรงพระจันทร์ครึ่งดวงสุดเก๋ ฝาพับแม่เหล็กซ่อนด้านใน สายสะพายปรับระดับได้ 5 ระดับ',
        material: 'Smooth Calfskin Vegan Leather',
        dimensions: '23 x 16 x 7 cm',
        color: 'Warm Almond',
        badge: 'BESTSELLER',
        is_active: true
    },
    {
        id: 'prod-015',
        sku: 'BAG-CRB-15',
        name: 'Vintage Postman Leather Messenger',
        name_th: 'กระเป๋าสะพายทรงบุรุษไปรษณีย์วินเทจ',
        category: 'crossbody',
        price: 3490.00,
        cost_price: 1650.00,
        stock: 11,
        image_url: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าสะพายหนังฟอกฝาดสไตล์วินเทจ ยิ่งใช้หนังยิ่งเงาสวย ทนทานนานนับสิบปี',
        material: 'Full Grain Waxed Leather',
        dimensions: '28 x 22 x 9 cm',
        color: 'Antique Brown',
        badge: 'HOT',
        is_active: true
    },
    {
        id: 'prod-016',
        sku: 'BAG-CRB-16',
        name: 'Nordic Minimalist Phone Bag',
        name_th: 'กระเป๋าสะพายใส่มือถือนอร์ดิก',
        category: 'crossbody',
        price: 990.00,
        cost_price: 390.00,
        stock: 40,
        image_url: 'https://images.unsplash.com/photo-1583623733237-4d5764a9dc82?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าใส่มือถือและบัตรใบกะทัดรัด น้ำหนักเบาพิเศษ พกพาสะดวกในวันชิลๆ',
        material: 'Soft PU Leather',
        dimensions: '12 x 19 x 3 cm',
        color: 'Dusty Mint',
        badge: 'NEW',
        is_active: true
    },
    {
        id: 'prod-017',
        sku: 'BAG-CRB-17',
        name: 'Celeste Accordion Crossbody',
        name_th: 'กระเป๋าสะพายข้างทรงหีบเพลง',
        category: 'crossbody',
        price: 2790.00,
        cost_price: 1250.00,
        stock: 15,
        image_url: 'https://images.unsplash.com/photo-1563903530908-afdd155d057a?auto=format&fit=crop&w=800&q=80',
        description: 'ช่องใส่ของแบ่ง 3 พับแบบหีบเพลง จุของได้เป็นระเบียบเรียบร้อย ทรงสวยไม่เสียทรง',
        material: 'Saffiano Leather & Gold Accents',
        dimensions: '22 x 16 x 8 cm',
        color: 'Burgundy Wine',
        badge: '',
        is_active: true
    },
    {
        id: 'prod-018',
        sku: 'BAG-CRB-18',
        name: 'Sport Utility Nylon Sling Bag',
        name_th: 'กระเป๋าสะพายข้างผ้าไนลอนกันน้ำ',
        category: 'crossbody',
        price: 1450.00,
        cost_price: 600.00,
        stock: 28,
        image_url: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าผ้าไนลอนกันน้ำ 100% ซิปกันน้ำ สายสะพายหนานุ่ม สไตล์สตรีทแฟชั่น',
        material: 'Ballistic Nylon 420D',
        dimensions: '26 x 17 x 6 cm',
        color: 'Matte Black',
        badge: 'HOT',
        is_active: true
    },
    {
        id: 'prod-019',
        sku: 'BAG-CRB-19',
        name: 'Chic Bohemian Fringe Crossbody',
        name_th: 'กระเป๋าสะพายข้างแต่งพู่โบฮีเมียน',
        category: 'crossbody',
        price: 2290.00,
        cost_price: 980.00,
        stock: 12,
        image_url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าหนังกลับแต่งพู่ยาวพลิ้วไหว สไตล์โบโฮชิค เข้ากับชุดเดรสและลุคท่องเที่ยว',
        material: 'Genuine Suede Leather',
        dimensions: '20 x 22 x 5 cm',
        color: 'Desert Sand Suede',
        badge: 'LIMITED',
        is_active: true
    },
    {
        id: 'prod-020',
        sku: 'BAG-CRB-20',
        name: 'Prestige Lock Metal Crossbody',
        name_th: 'กระเป๋าสะพายข้างล็อคทองหรู',
        category: 'crossbody',
        price: 3190.00,
        cost_price: 1450.00,
        stock: 14,
        image_url: 'https://images.unsplash.com/photo-1572196298647-45300069b208?auto=format&fit=crop&w=800&q=80',
        description: 'ตัวล็อคโลหะสีทองอร่ามดีไซน์โมเดิร์น หนังลายจระเข้เรียบหรู เสริมความมั่นใจ',
        material: 'Croc-Embossed Vegan Leather',
        dimensions: '25 x 17 x 7 cm',
        color: 'Emerald Croc',
        badge: 'BESTSELLER',
        is_active: true
    },

    // --- 3. SHOULDER BAGS (10 items) ---
    {
        id: 'prod-021',
        sku: 'BAG-SHO-04',
        name: 'Signature Baguette Shoulder Bag',
        name_th: 'กระเป๋าสะพายไหล่ทรงบาแก็ตต์',
        category: 'shoulder',
        price: 3200.00,
        cost_price: 1400.00,
        stock: 10,
        image_url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าสะพายไหล่ทรงเก๋สไตล์ฝรั่งเศส ให้ลุคเรียบหรูดูแพง น้ำหนักเบาคล่องตัว',
        material: 'Italian Smooth Leather',
        dimensions: '27 x 14 x 6 cm',
        color: 'Caramel Tan',
        badge: 'HOT',
        is_active: true
    },
    {
        id: 'prod-022',
        sku: 'BAG-FLA-06',
        name: 'Elegance Quilted Flap Bag',
        name_th: 'กระเป๋าหนังลายควิลต์โซ่ทอง',
        category: 'shoulder',
        price: 3990.00,
        cost_price: 1800.00,
        stock: 12,
        image_url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าหนังลายควิลต์ประดับสายโซ่ทองหรูหรา ซับในกำมะหยี่ เหมาะสำหรับออกงาน',
        material: 'Lambskin Touch PU & Chain',
        dimensions: '26 x 16 x 8 cm',
        color: 'Champagne Beige',
        badge: 'BESTSELLER',
        is_active: true
    },
    {
        id: 'prod-023',
        sku: 'BAG-HOB-10',
        name: 'Modern Crescent Moon Hobo Bag',
        name_th: 'กระเป๋าทรงพระจันทร์เสี้ยว',
        category: 'shoulder',
        price: 2790.00,
        cost_price: 1250.00,
        stock: 16,
        image_url: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าสะพายทรงพระจันทร์เสี้ยว มินิมอลสายเกาหลี หนังนุ่มน้ำหนักเบา จุของครบ',
        material: 'Soft Vegan Leather',
        dimensions: '30 x 20 x 8 cm',
        color: 'Cream Ivory',
        badge: 'BESTSELLER',
        is_active: true
    },
    {
        id: 'prod-024',
        sku: 'BAG-SHO-24',
        name: 'Athena Chain Strap Shoulder Flap',
        name_th: 'กระเป๋าสะพายไหล่สายโซ่เอเธน่า',
        category: 'shoulder',
        price: 3650.00,
        cost_price: 1600.00,
        stock: 14,
        image_url: 'https://images.unsplash.com/photo-1597633425046-08f5110420b5?auto=format&fit=crop&w=800&q=80',
        description: 'สายโซ่คู่ปรับสะพายเดี่ยวหรือคู่ได้ ฝาพับทรงมน หนังเงาประกายหรูหรา',
        material: 'Glossy Calfskin Leather',
        dimensions: '25 x 15 x 7 cm',
        color: 'Deep Cherry',
        badge: 'NEW',
        is_active: true
    },
    {
        id: 'prod-025',
        sku: 'BAG-SHO-25',
        name: 'Parisienne Croissant Leather Bag',
        name_th: 'กระเป๋าหนังทรงครัวซองต์สไตล์ปารีส',
        category: 'shoulder',
        price: 2950.00,
        cost_price: 1350.00,
        stock: 18,
        image_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
        description: 'ดีไซน์จับจีบทรงครัวซองต์ยอดฮิต หนังนุ่มมาก ให้ลุคแฟชั่นนิสต้าตัวจริง',
        material: 'Ultra Soft Nappa Leather',
        dimensions: '32 x 18 x 10 cm',
        color: 'Warm Butter / Cream',
        badge: 'HOT',
        is_active: true
    },
    {
        id: 'prod-026',
        sku: 'BAG-SHO-26',
        name: 'Vogue Ruched Handle Shoulder Bag',
        name_th: 'กระเป๋าสะพายไหล่สายย่นแฟชั่น',
        category: 'shoulder',
        price: 1990.00,
        cost_price: 850.00,
        stock: 20,
        image_url: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
        description: 'สายสะพายไหล่ออกแบบย่นมีมิติ น้ำหนักเบา ดีไซน์ล้ำสมัยใส่กับชุดไหนก็เด่น',
        material: 'Matte Silk Poly & Leather',
        dimensions: '26 x 14 x 6 cm',
        color: 'Lilac Lavender',
        badge: 'NEW',
        is_active: true
    },
    {
        id: 'prod-027',
        sku: 'BAG-SHO-27',
        name: 'Royal Heritage Structured Shoulder',
        name_th: 'กระเป๋าสะพายไหล่ทรงเหลี่ยมรอยัล',
        category: 'shoulder',
        price: 4350.00,
        cost_price: 2100.00,
        stock: 8,
        image_url: 'https://images.unsplash.com/photo-1581605405669-fcdf81165afa?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าหนังทรงเหลี่ยมตั้งแข็งแรง อะไหล่รมดำพรีเมียม สวยคลาสสิกข้ามกาลเวลา',
        material: 'Hand-dyed Saddle Leather',
        dimensions: '28 x 19 x 8 cm',
        color: 'Ebony Black',
        badge: 'LIMITED',
        is_active: true
    },
    {
        id: 'prod-028',
        sku: 'BAG-SHO-28',
        name: 'Solstice Double-Zip Shoulder Bag',
        name_th: 'กระเป๋าสะพายไหล่ซิปคู่โซลสติซ',
        category: 'shoulder',
        price: 2490.00,
        cost_price: 1100.00,
        stock: 22,
        image_url: 'https://images.unsplash.com/photo-1559563458-527698bf5295?auto=format&fit=crop&w=800&q=80',
        description: 'ช่องซิปคู่แยกหน้าหลัง จุของได้เยอะ หยิบของสะดวก สายสะพายหนังแบนไม่เจ็บไหล่',
        material: 'Grained Vegan Leather',
        dimensions: '29 x 16 x 9 cm',
        color: 'Sand Beige',
        badge: '',
        is_active: true
    },
    {
        id: 'prod-029',
        sku: 'BAG-SHO-29',
        name: 'Chic Velvet Evening Shoulder Pochette',
        name_th: 'กระเป๋าสะพายไหล่กำมะหยี่ออกงาน',
        category: 'shoulder',
        price: 2250.00,
        cost_price: 950.00,
        stock: 15,
        image_url: 'https://images.unsplash.com/photo-1506152983158-b4a74a01c721?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าโพแชตกำมะหยี่เนื้อเงา ประดับคริสตัลที่หัวซิป สวยสะกดทุกสายตาในงานกลางคืน',
        material: 'Silk Velvet & Crystal Zipper',
        dimensions: '24 x 13 x 5 cm',
        color: 'Midnight Navy Velvet',
        badge: 'LIMITED',
        is_active: true
    },
    {
        id: 'prod-030',
        sku: 'BAG-SHO-30',
        name: 'Monogram Tweed Vintage Shoulder',
        name_th: 'กระเป๋าสะพายไหล่ผ้าทวีตโมโนแกรม',
        category: 'shoulder',
        price: 3100.00,
        cost_price: 1350.00,
        stock: 17,
        image_url: 'https://images.unsplash.com/photo-1569388330292-79cc1ec67270?auto=format&fit=crop&w=800&q=80',
        description: 'ผ้าทวีตทอมือลายตารางหรูหรา ขอบหนังแท้สีเบจ สไตล์คุณหนูลักชูรี่',
        material: 'Woven Tweed Fabric & Leather',
        dimensions: '27 x 15 x 6.5 cm',
        color: 'Tweed Ivory & Gold',
        badge: 'HOT',
        is_active: true
    },

    // --- 4. BACKPACKS (6 items) ---
    {
        id: 'prod-031',
        sku: 'BAG-BPK-07',
        name: 'City Explorer Roll-top Backpack',
        name_th: 'เป้สะพายหลังกันน้ำดีไซน์คนเมือง',
        category: 'backpack',
        price: 2890.00,
        cost_price: 1300.00,
        stock: 20,
        image_url: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=800&q=80',
        description: 'เป้สะพายหลังสไตล์ Roll-top ช่องบุกันกระแทกใส่ Laptop 15.6 นิ้ว กันน้ำ 100%',
        material: 'Cordura 500D Waterproof',
        dimensions: '45 x 30 x 15 cm',
        color: 'Space Grey',
        badge: 'NEW',
        is_active: true
    },
    {
        id: 'prod-032',
        sku: 'BAG-BPK-32',
        name: 'Heritage Leather Daypack',
        name_th: 'เป้หนังแท้สไตล์คลาสสิกเดย์แพ็ค',
        category: 'backpack',
        price: 4890.00,
        cost_price: 2300.00,
        stock: 9,
        image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
        description: 'เป้หนังแท้ทั้งใบ ฝาปิดพร้อมสายรัดเข็มขัดคู่ สวยคลาสสิก เหมาะสำหรับเดินทางและทำงาน',
        material: 'Top Grain Vintage Leather',
        dimensions: '40 x 30 x 14 cm',
        color: 'Cognac Saddle',
        badge: 'BESTSELLER',
        is_active: true
    },
    {
        id: 'prod-033',
        sku: 'BAG-BPK-33',
        name: 'Mini Chic Urban Leather Backpack',
        name_th: 'มินิเป้หนังแฟชั่นสำหรับผู้หญิง',
        category: 'backpack',
        price: 2390.00,
        cost_price: 1050.00,
        stock: 25,
        image_url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
        description: 'เป้ขนาดกะทัดรัดน่ารัก สายสะพายสามารถปรับเป็นสะพายข้างได้ 2-in-1',
        material: 'Soft Pebble Vegan Leather',
        dimensions: '26 x 22 x 10 cm',
        color: 'Blush Pink',
        badge: 'HOT',
        is_active: true
    },
    {
        id: 'prod-034',
        sku: 'BAG-BPK-34',
        name: 'Commuter Slim Laptop Backpack',
        name_th: 'เป้ใส่แล็ปท็อปทรงสลิมคนทำงาน',
        category: 'backpack',
        price: 2190.00,
        cost_price: 900.00,
        stock: 22,
        image_url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
        description: 'เป้ทรงบางเฉียบ เหมาะขึ้นรถไฟฟ้า มีพอร์ตชาร์จ USB ด้านข้าง และช่องซ่อนเงินด้านหลัง',
        material: 'Water-repellent Oxford Poly',
        dimensions: '43 x 29 x 10 cm',
        color: 'Midnight Black',
        badge: '',
        is_active: true
    },
    {
        id: 'prod-035',
        sku: 'BAG-BPK-35',
        name: 'Nomad Waxed Canvas Outdoor Backpack',
        name_th: 'เป้ผ้าแคนวาสเคลือบแว็กซ์สไตล์เอาท์ดอร์',
        category: 'backpack',
        price: 3690.00,
        cost_price: 1700.00,
        stock: 14,
        image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
        description: 'ผ้าแคนวาสหนาเคลือบแว็กซ์กันน้ำ ทนทานทุกสภาพอากาศ ตกแต่งด้วยหนังแท้หนาพิเศษ',
        material: 'Waxed Heavy Canvas 18oz & Leather',
        dimensions: '44 x 32 x 16 cm',
        color: 'Khaki Green',
        badge: 'LIMITED',
        is_active: true
    },
    {
        id: 'prod-036',
        sku: 'BAG-BPK-36',
        name: 'Starlight Metallic Fashion Backpack',
        name_th: 'เป้สะพายหลังหนังเมทัลลิกประกายดาว',
        category: 'backpack',
        price: 2550.00,
        cost_price: 1100.00,
        stock: 16,
        image_url: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=80',
        description: 'เป้แฟชั่นหนังเคลือบประกายเมทัลลิกวิบวับ เพิ่มความสนุกสนานให้กับการแต่งตัว',
        material: 'Metallic Coated Leather',
        dimensions: '28 x 24 x 11 cm',
        color: 'Rose Gold Metallic',
        badge: 'NEW',
        is_active: true
    },

    // --- 5. TRAVEL & DUFFEL BAGS (6 items) ---
    {
        id: 'prod-037',
        sku: 'BAG-TRV-05',
        name: 'Weekend Duffel Travel Bag',
        name_th: 'กระเป๋าเดินทางสไตล์วีคเอนเดอร์',
        category: 'travel',
        price: 4500.00,
        cost_price: 2200.00,
        stock: 8,
        image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าเดินทางความจุ 45L ผ้ากันละอองน้ำ ผสมหนังแท้ ช่องใส่รองเท้าแยกด้านข้าง',
        material: 'Waterproof Ballistic Nylon & Leather',
        dimensions: '52 x 30 x 26 cm',
        color: 'Olive Green & Leather',
        badge: 'LIMITED',
        is_active: true
    },
    {
        id: 'prod-038',
        sku: 'BAG-TRV-38',
        name: 'Voyager All-Leather Weekender',
        name_th: 'กระเป๋าเดินทางหนังแท้รุ่นวอยเอเจอร์',
        category: 'travel',
        price: 6890.00,
        cost_price: 3500.00,
        stock: 6,
        image_url: 'https://images.unsplash.com/photo-1524498250077-390f9e378fc0?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าเดินทางหนังวัวแท้ทั้งใบ ระดับไฮเอนด์ สำหรับนักเดินทางผู้รักความหรูหรา',
        material: 'Full Grain Italian Leather',
        dimensions: '55 x 32 x 28 cm',
        color: 'Rich Dark Chocolate',
        badge: 'BESTSELLER',
        is_active: true
    },
    {
        id: 'prod-039',
        sku: 'BAG-TRV-39',
        name: 'Aerolite Foldable Flight Duffle',
        name_th: 'กระเป๋าพับได้สำหรับพกพาขึ้นเครื่อง',
        category: 'travel',
        price: 1250.00,
        cost_price: 490.00,
        stock: 45,
        image_url: 'https://images.unsplash.com/photo-1590736704728-f4730bb30770?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าเสริมพับเก็บใส่ซองเล็กได้ เสียบกับคันชักกระเป๋าล้อลากได้พอดี',
        material: 'Ultra-light Ripstop Nylon',
        dimensions: '48 x 32 x 20 cm',
        color: 'Slate Blue',
        badge: 'HOT',
        is_active: true
    },
    {
        id: 'prod-040',
        sku: 'BAG-TRV-40',
        name: 'Sport & Gym Duffle with Shoe Pocket',
        name_th: 'กระเป๋ายิมและกีฬาช่องแยกใส่รองเท้า',
        category: 'travel',
        price: 1790.00,
        cost_price: 750.00,
        stock: 30,
        image_url: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าออกกำลังกายและทริป 2 วัน ช่องระบายอากาศสำหรับรองเท้า และช่องใส่ชุดเปียก',
        material: 'Heavy Duty Oxford & TPU',
        dimensions: '46 x 26 x 24 cm',
        color: 'Charcoal / Neon Trim',
        badge: '',
        is_active: true
    },
    {
        id: 'prod-041',
        sku: 'BAG-TRV-41',
        name: 'Safari Canvas & Leather Holdall',
        name_th: 'กระเป๋าเดินทางแคนวาสสไตล์ซาฟารี',
        category: 'travel',
        price: 3890.00,
        cost_price: 1800.00,
        stock: 12,
        image_url: 'https://images.unsplash.com/photo-1575032617751-6ddec2089882?auto=format&fit=crop&w=800&q=80',
        description: 'ผ้าแคนวาสลายทวิลหนาพิเศษ แต่งสายหนังแท้และหมุดทองเหลือง แข็งแรงทนทาน',
        material: 'Twill Canvas & Saddle Leather',
        dimensions: '50 x 28 x 25 cm',
        color: 'Desert Sand & Tan',
        badge: 'HOT',
        is_active: true
    },
    {
        id: 'prod-042',
        sku: 'BAG-TRV-42',
        name: 'Garment Suit Carrier Travel Bag',
        name_th: 'กระเป๋าเดินทางเก็บสูทและชุดราตรี 2-in-1',
        category: 'travel',
        price: 4290.00,
        cost_price: 2000.00,
        stock: 10,
        image_url: 'https://images.unsplash.com/photo-1598532163257-ae3c6b2524b6?auto=format&fit=crop&w=800&q=80',
        description: 'กางออกเป็นถุงคลุมสูทไม่ให้ยับ พับประกอบเป็นกระเป๋าดัฟเฟิลเดินทางได้ทันที',
        material: 'Anti-wrinkle Waterproof Fabric',
        dimensions: '54 x 30 x 28 cm',
        color: 'Matte Executive Black',
        badge: 'NEW',
        is_active: true
    },

    // --- 6. MINI BAGS, WALLETS & CLUTCHES (8 items) ---
    {
        id: 'prod-043',
        sku: 'BAG-WLT-09',
        name: 'Compact Multi-card Clutch Wallet',
        name_th: 'กระเป๋าคลัตช์ใส่บัตรและมือถือ',
        category: 'mini',
        price: 1150.00,
        cost_price: 480.00,
        stock: 25,
        image_url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าสตางค์และคลัตช์ขนาดพกพา ใส่การ์ดได้ 12 ใบ พร้อมช่องซิปเหรียญและสายคล้องข้อมือ',
        material: 'Cross-grain Leather',
        dimensions: '19 x 10 x 2.5 cm',
        color: 'Dusty Rose',
        badge: 'NEW',
        is_active: true
    },
    {
        id: 'prod-044',
        sku: 'BAG-MIN-44',
        name: 'Prestige Zip-Around Long Wallet',
        name_th: 'กระเป๋าสตางค์ซิปรอบหนังแท้ทรงยาว',
        category: 'mini',
        price: 1850.00,
        cost_price: 800.00,
        stock: 28,
        image_url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
        description: 'ซิปรูดรอบปกป้องของด้านใน ใส่ธนบัตรไม่ต้องพับ มีช่องใส่เหรียญและบัตร 16 ช่อง',
        material: 'Full Grain Saffiano Leather',
        dimensions: '20 x 10.5 x 2.5 cm',
        color: 'Classic Black',
        badge: 'BESTSELLER',
        is_active: true
    },
    {
        id: 'prod-045',
        sku: 'BAG-MIN-45',
        name: 'Slim MagSafe Leather Cardholder',
        name_th: 'กระเป๋าเก็บบัตรทรงบางเฉียบแม่เหล็ก',
        category: 'mini',
        price: 690.00,
        cost_price: 250.00,
        stock: 50,
        image_url: 'https://images.unsplash.com/photo-1614179689702-355944cf0918?auto=format&fit=crop&w=800&q=80',
        description: 'ที่ใส่บัตรหนังแท้ขนาดบางเฉียบ จุบัตรได้ 6 ใบ พกใส่กระเป๋าเสื้อได้พอดี',
        material: 'Vegetable Tanned Leather',
        dimensions: '10 x 7.5 x 0.5 cm',
        color: 'Caramel & Gold',
        badge: 'HOT',
        is_active: true
    },
    {
        id: 'prod-046',
        sku: 'BAG-MIN-46',
        name: 'Glamour Satin Evening Minaudière',
        name_th: 'กระเป๋าคลัตช์ซาตินประดับเพชรออกงาน',
        category: 'mini',
        price: 2690.00,
        cost_price: 1100.00,
        stock: 15,
        image_url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าคลัตช์กล่องหุ้มผ้าซาตินเงางาม ตัวล็อคเพชรคริสตัล มีสายโซ่สะพายถอดได้',
        material: 'Duchess Satin & Austrian Crystals',
        dimensions: '18 x 11 x 5 cm',
        color: 'Silver Sparkle',
        badge: 'LIMITED',
        is_active: true
    },
    {
        id: 'prod-047',
        sku: 'BAG-MIN-47',
        name: 'Bespoke Coin & Key Pouch',
        name_th: 'กระเป๋าใส่เหรียญและพวงกุญแจหนังแท้',
        category: 'mini',
        price: 790.00,
        cost_price: 290.00,
        stock: 35,
        image_url: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าจิ๋วใส่กุญแจบ้านและเหรียญ มีห่วงคล้องกระเป๋าใหญ่ สวยน่ารักและใช้ประโยชน์ได้จริง',
        material: 'Pebble Leather & Brass Keyring',
        dimensions: '11 x 7 x 2 cm',
        color: 'Honey Mustard',
        badge: '',
        is_active: true
    },
    {
        id: 'prod-048',
        sku: 'BAG-MIN-48',
        name: 'Trifold Compact Leather Wallet',
        name_th: 'กระเป๋าสตางค์พับสามทบขนาดกะทัดรัด',
        category: 'mini',
        price: 1390.00,
        cost_price: 580.00,
        stock: 30,
        image_url: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าสตางค์พับสามตอน ขนาดเล็กจิ๋วแต่ใส่แบงก์พันได้ครบ ช่องใส่บัตร 8 ช่อง',
        material: 'Smooth Calfskin',
        dimensions: '10 x 8 x 3 cm',
        color: 'Sage Green',
        badge: 'NEW',
        is_active: true
    },
    {
        id: 'prod-049',
        sku: 'BAG-MIN-49',
        name: 'Velvet Ribbon Wristlet Clutch',
        name_th: 'กระเป๋าคลัตช์คล้องมือโบว์กำมะหยี่',
        category: 'mini',
        price: 1590.00,
        cost_price: 650.00,
        stock: 22,
        image_url: 'https://images.unsplash.com/photo-1506152983158-b4a74a01c721?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าคลัตช์คล้องข้อมือตกแต่งโบว์กำมะหยี่หวานซ่อนเปรี้ยว เหมาะกับงานปาร์ตี้',
        material: 'Premium Velvet & Satin Lining',
        dimensions: '22 x 14 x 3 cm',
        color: 'Ruby Red Velvet',
        badge: 'HOT',
        is_active: true
    },
    {
        id: 'prod-050',
        sku: 'BAG-MIN-50',
        name: 'Aurelia Metallic Card & Lipstick Case',
        name_th: 'กระเป๋ามินิใส่ลิปสติกและการ์ดออเรเลีย',
        category: 'mini',
        price: 1290.00,
        cost_price: 520.00,
        stock: 26,
        image_url: 'https://images.unsplash.com/photo-1597633425046-08f5110420b5?auto=format&fit=crop&w=800&q=80',
        description: 'กระเป๋าไซส์ไมโครพร้อมกระจกเงาด้านใน ใส่ลิปสติกและบัตร 2 ใบ สายโซ่สะพายครอสบอดี้ได้',
        material: 'Metallic Microfiber Leather',
        dimensions: '11 x 9 x 4 cm',
        color: 'Champagne Gold',
        badge: 'LIMITED',
        is_active: true
    }
];
